# Configuration for SwiftLint - Swift code style and quality enforcement
disabled_rules: # Rules to disable based on project preferences
  - trailing_whitespace
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - force_cast
  - type_body_length

included: # Directories to include in linting
  - iOS
  - Shared

excluded: # Directories to exclude from linting
  - Pods
  - .build
  - .swiftpm
  - Carthage
  - vendor

# Additional recommended configurations
opt_in_rules: # Enable optional rules for better code quality
  - empty_count
  - empty_string
  - closure_spacing

reporter: "xcode" # Output format compatible with Xcode
