combine_and_report:
  runs-on: ubuntu-22.04
  needs: [analyze_cpp, analyze_swift, analyze_infer]
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref || github.ref }}

    - name: Download Cppcheck results
      uses: actions/download-artifact@v3
      with:
        name: cppcheck-results
        path: artifacts/cppcheck-results

    - name: Download SwiftLint results
      uses: actions/download-artifact@v3
      with:
        name: swiftlint-results
        path: artifacts/swiftlint-results

    - name: Download Infer results
      uses: actions/download-artifact@v3
      with:
        name: infer-results
        path: artifacts/infer-results

    - name: Combine and Process Results
      run: |
        mkdir -p analysis-reports
        timestamp=$(date +%Y%m%d-%H%M%S)

        # Combine all reports with headers
        echo "# Code Analysis Report - $timestamp" > analysis-reports/combined_report_${timestamp}.md
        echo "## Cppcheck Results" >> analysis-reports/combined_report_${timestamp}.md
        cat artifacts/cppcheck-results/cppcheck_errors.txt >> analysis-reports/combined_report_${timestamp}.md 2>/dev/null || echo "No Cppcheck results found"

        echo "## SwiftLint Results" >> analysis-reports/combined_report_${timestamp}.md
        cat artifacts/swiftlint-results/swiftlint_errors.txt >> analysis-reports/combined_report_${timestamp}.md 2>/dev/null || echo "No SwiftLint results found"

        echo "## Infer Results" >> analysis-reports/combined_report_${timestamp}.md
        cat artifacts/infer-results/infer_errors.txt >> analysis-reports/combined_report_${timestamp}.md 2>/dev/null || echo "No Infer results found"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add code analysis report for ${{ github.sha }}"
        branch: "analysis-report/${{ github.run_id }}"
        delete-branch: true
        title: "Code Analysis Report - ${{ github.sha }}"
        body: |
          Automated code analysis report generated on ${{ github.event_name }}.
          Commit: ${{ github.sha }}
          Contains results from Cppcheck, SwiftLint, and Infer.
          See attached report for details.
        labels: |
          automated
          code-quality
        path: analysis-reports/combined_report_${timestamp}.md