name: Check MobileProvision Expiry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-profiles:
    runs-on: macos-latest  # macOS is required for the `security` command
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run expiry check script
        run: |
          python check_mobileprovisions.py